//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Security.Cryptography;
    using System.Linq;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Mensagens = new HashSet<Mensagens>();
        }

        public Users(string  username, byte[] saltedPasswordHash, byte[] salt)
        {
            this.Username = username;
            this.SaltedPasswordHash = saltedPasswordHash;
            this.Salt = salt;
            this.Mensagens = new HashSet<Mensagens>();
        }
        public int IdUser { get; set; }
        public string Username { get; set; }
        private byte[] SaltedPasswordHash { get; set; }
        private byte[] Salt { get; set; }
        public System.DateTime dtCreation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensagens> Mensagens { get; set; }

        public bool checkedSaltPassword(byte[] SaltedPassword)
        {
            return this.SaltedPasswordHash.SequenceEqual(SaltedPassword);
        }
    }
}
